# Generated by Django 6.0.6 on 2026-06-11 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coverage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(help_text='Medical record number (minimum necessary identifier).', max_length=20, verbose_name='MRN')),
                ('patient_initials', models.CharField(blank=True, max_length=8)),
                ('machine', models.CharField(blank=True, max_length=60)),
                ('treatment_site', models.CharField(help_text='e.g. Left breast, Prostate, Brain mets.', max_length=120)),
                ('technique', models.CharField(blank=True, help_text='e.g. VMAT, 3D, SBRT, DIBH.', max_length=60)),
                ('fractions', models.CharField(blank=True, help_text='e.g. 28 fx, 5 fx.', max_length=30)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Plan in progress'), ('ready', 'Ready for treatment'), ('started', 'Started'), ('held', 'On hold')], default='pending', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coverage.location')),
                ('physicist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coverage.physicist')),
            ],
            options={
                'ordering': ['start_date', 'location__order'],
            },
        ),
        migrations.CreateModel(
            name='SpecialProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(blank=True, max_length=20, verbose_name='MRN')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_prep', 'In preparation'), ('done', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup_physicist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_procedures_backup', to='coverage.physicist')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coverage.location')),
                ('physicist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_procedures', to='coverage.physicist')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coverage.proceduretype')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
    ]
