# Generated by Django 6.0.6 on 2026-06-11 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'Link categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.CharField(help_text='http(s) URL, or a UNC/file path like \\\\fileserver\\physics (shown with a copy button).', max_length=500)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('keywords', models.CharField(blank=True, help_text='Extra search terms, comma separated.', max_length=255)),
                ('icon', models.CharField(blank=True, default='link', help_text='Icon key from the built-in set (link, beam, database, document, citrix, folder, report, form).', max_length=40)),
                ('pinned', models.BooleanField(default=False, help_text='Pinned links appear in Quick Links on the home page.')),
                ('open_in_new_tab', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='linkhub.linkcategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'title'],
            },
        ),
    ]
