# Generated by Django 6.0.6 on 2026-06-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coverage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Person or team name.', max_length=150)),
                ('kind', models.CharField(choices=[('engineer', 'Field Service Engineer'), ('vendor', 'Vendor Support Line'), ('internal', 'Internal (Biomed / IT / Facilities)'), ('other', 'Other')], default='engineer', max_length=20)),
                ('organization', models.CharField(blank=True, help_text='Varian, Elekta, Sun Nuclear, hospital IT, ...', max_length=150)),
                ('systems', models.CharField(blank=True, help_text='Equipment / systems covered, e.g. TrueBeam 1-3, ARIA, HDR afterloader.', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('after_hours_phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('support_portal_url', models.URLField(blank=True, help_text='e.g. Varian MyVarian / Elekta Care portal case link.')),
                ('contract_notes', models.CharField(blank=True, help_text='Service contract / entitlement notes.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locations', models.ManyToManyField(blank=True, related_name='service_contacts', to='coverage.location')),
            ],
            options={
                'ordering': ['organization', 'name'],
            },
        ),
    ]
