# Generated by Django 6.0.6 on 2026-06-11 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Matches a query module in apps/reporting/queries/.', unique=True)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('aria', 'ARIA (Varian)'), ('mosaiq', 'MOSAIQ (Elekta)'), ('intranet', 'Intranet database')], max_length=10)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_dev', 'In development'), ('live', 'Live'), ('disabled', 'Disabled')], default='planned', max_length=10)),
                ('owner_notes', models.TextField(blank=True, help_text='SQL notes, table names, ticket links.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Leave empty to allow everyone in the Reporting Access group.', to='auth.group')),
            ],
            options={
                'ordering': ['source', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=False)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='reporting.reportdefinition')),
                ('run_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
    ]
